import React from "react";
import ReactDOM from "react-dom/client";

/*
* Header
   - Logo
   - Nav Items
* Body
   - Search
   - ResturantContainer
      -ResturantCard
        - Img
        - Ratings, Cusine, Time, Price
        
* Footer
   - Copyright
   - Links
   - Address
   - Contact
*/

const Header = () => {
  return (
    <div className="header container">
      <div className="logo-container">
        <img
          className="logo"
          src="https://www.logodesign.net/logo/smoking-burger-with-lettuce-3624ld.png"
        />
      </div>
      <div className="nav-items">
        <ul>
          <li className="home">Home</li>
          <li className="about">About Us </li>
          <li className="contact">Contact Us </li>
          <li className="cart">Cart</li>
        </ul>
      </div>
    </div>
  );
};

const Footer = () => {
  return (
    <div className="footer-container">
      <h4>Copyright</h4>
      <h4>Links</h4>
      <h4>Address</h4>
      <h4>Contact</h4>
    </div>
  );
};

const resList = [
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "256957",
        name: "Shanmukha Restaurant",
        uuid: "c1972fbf-2e19-42d6-ac49-54f412f78d86",
        city: "1",
        area: "Jayanagar",
        totalRatingsString: "",
        cloudinaryImageId: "c5howge9hbdor7uqf949",
        cuisines: [
          "Biryani",
          "Hyderabadi",
          "Andhra",
          "North Indian",
          "South Indian",
          "Chinese",
          "Tandoor",
          "Seafood",
          "Beverages",
        ],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: "26 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "shanmukha-restaurant-jayanagar-jayanagar",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "9th Block",
        parentId: 9954,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 6600,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6600,
          message: "",
          title: "Delivery Charge",
          amount: "6600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7760994~p=1~eid=00000189-d11b-0298-1d84-4c9d003d0117~srvts=1691430355608~83649",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              description: "",
              shortDescription: "options available",
              fontColor: "#7E808C",
            },
          ],
        },
        lastMileTravelString: "5.5 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=256957&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 0,
          lastMileDistance: 5.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.0",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "428",
        name: "Biryani Pot",
        uuid: "6db20a8b-dd85-4148-b750-107169f7f826",
        city: "1",
        area: "Btm Layout",
        totalRatingsString: "",
        cloudinaryImageId: "mdipoyzfzsa7n7igskht",
        cuisines: ["North Indian", "Biryani"],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 19,
        minDeliveryTime: 19,
        maxDeliveryTime: 19,
        slaString: "19 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "biryani-pot-madiwala-junction-btm",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Maruti Nagar",
        parentId: 21798,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 3300,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3300,
          message: "",
          title: "Delivery Charge",
          amount: "3300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7729520~p=2~eid=00000189-d11b-0298-1d84-4c9e003d0210~srvts=1691430355608~83649",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              description: "",
              shortDescription: "options available",
              fontColor: "#7E808C",
            },
          ],
        },
        lastMileTravelString: "1.9 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=428&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 19,
          minDeliveryTime: 19,
          maxDeliveryTime: 19,
          lastMileTravel: 0,
          lastMileDistance: 1.9,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.9",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "342758",
        name: 'Sahukar Biryani "Biryani Royal"',
        uuid: "e579b5d0-1488-4a78-bb0a-b372f5067db8",
        city: "1",
        area: "Koramangala",
        totalRatingsString: "",
        cloudinaryImageId: "fugqadr8krirxpta7x8e",
        cuisines: ["Indian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        slaString: "23 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "biriyani-royale-hsr-hsr",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "1st Block",
        parentId: 315041,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 4800,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4800,
          message: "",
          title: "Delivery Charge",
          amount: "4800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7729851~p=3~eid=00000189-d11b-0298-1d84-4c9f003d0303~srvts=1691430355608~83649",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.5 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=342758&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 23,
          minDeliveryTime: 23,
          maxDeliveryTime: 23,
          lastMileTravel: 0,
          lastMileDistance: 2.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.0",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "14837",
        name: "High Street",
        uuid: "d4d8f90b-5531-401b-9d66-99f425a6f825",
        city: "1",
        area: "HSR Layout",
        totalRatingsString: "",
        cloudinaryImageId: "qqwbp7qd3ujocqjhqxvt",
        cuisines: ["Biryani", "North Indian", "Tandoor", "Andhra", "Chinese"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        slaString: "25 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "high-street-hsr-hsr",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "7th Sector",
        parentId: 11938,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 4900,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4900,
          message: "",
          title: "Delivery Charge",
          amount: "4900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7773787~p=4~eid=00000189-d11b-0298-1d84-4ca0003d041c~srvts=1691430355608~83649",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.2 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=14837&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 25,
          minDeliveryTime: 25,
          maxDeliveryTime: 25,
          lastMileTravel: 0,
          lastMileDistance: 4.2,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "227179",
        name: "RR Donne Biryani",
        uuid: "fb9337f9-47e2-4bbb-9dc9-94c803d86c17",
        city: "1",
        area: "Btm Layout",
        totalRatingsString: "",
        cloudinaryImageId: "uughlfbnykdtvefbmhdm",
        cuisines: [
          "Biryani",
          "Andhra",
          "South Indian",
          "Desserts",
          "Kebabs",
          "Beverages",
          "Kerala",
          "Indian",
        ],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 15,
        minDeliveryTime: 15,
        maxDeliveryTime: 15,
        slaString: "15 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "game-of-starters-btm-btm",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Madiwala",
        parentId: 172705,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 3300,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3300,
          message: "",
          title: "Delivery Charge",
          amount: "3300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7816484~p=5~eid=00000189-d11b-0298-1d84-4ca1003d0522~srvts=1691430355608~83649",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.8 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=227179&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 15,
          minDeliveryTime: 15,
          maxDeliveryTime: 15,
          lastMileTravel: 0,
          lastMileDistance: 1.8,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.9",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "252782",
        name: "Aramane Donne Biriyani",
        uuid: "39f8f363-186a-4be8-8fdd-e5ea5d788fc0",
        city: "1",
        area: "Koramangala",
        totalRatingsString: "",
        cloudinaryImageId: "bqzix8f33km3nvqtn2uz",
        cuisines: ["Indian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 17,
        minDeliveryTime: 17,
        maxDeliveryTime: 17,
        slaString: "17 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "aramane-donne-biriyani-koramangala-koramangala",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "8th Block",
        parentId: 7133,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 3300,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3300,
          message: "",
          title: "Delivery Charge",
          amount: "3300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.4 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=252782&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 17,
          minDeliveryTime: 17,
          maxDeliveryTime: 17,
          lastMileTravel: 0,
          lastMileDistance: 1.4,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "604",
        name: "Aalishan Restaurant & Caterer",
        uuid: "3a63a7e6-0042-4abf-9c9b-1e1ce5ac4c7e",
        city: "1",
        area: "Koramangala",
        totalRatingsString: "",
        cloudinaryImageId: "1921d9e6b05f56462ffe771cdd0fb10e",
        cuisines: ["Mughlai", "North Indian"],
        tags: [],
        costForTwo: 29000,
        costForTwoString: "₹290 FOR TWO",
        deliveryTime: 17,
        minDeliveryTime: 17,
        maxDeliveryTime: 17,
        slaString: "17 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "aalishan-restaurant-caterer-7th-block-koramangala",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "7th Block",
        parentId: 21072,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 4800,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4800,
          message: "",
          title: "Delivery Charge",
          amount: "4800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.2 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=604&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 17,
          minDeliveryTime: 17,
          maxDeliveryTime: 17,
          lastMileTravel: 0,
          lastMileDistance: 1.2,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "229",
        name: "Meghana Foods",
        uuid: "4fdd19e2-5d0f-4bde-9c7f-dc3e8d36021f",
        city: "1",
        area: "Koramangala",
        totalRatingsString: "",
        cloudinaryImageId: "xqwpuhgnsaf18te7zvtv",
        cuisines: [
          "Biryani",
          "Andhra",
          "South Indian",
          "North Indian",
          "Chinese",
          "Seafood",
        ],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 14,
        minDeliveryTime: 14,
        maxDeliveryTime: 14,
        slaString: "14 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "meghana-foods-5th-block-koramangala",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "5th Block",
        parentId: 635,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 3300,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3300,
          message: "",
          title: "Delivery Charge",
          amount: "3300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.4 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=229&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 14,
          minDeliveryTime: 14,
          maxDeliveryTime: 14,
          lastMileTravel: 0,
          lastMileDistance: 1.4,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "139558",
        name: "Dindigul Thalappakatti",
        uuid: "b94386c7-445c-4598-bee5-bdbb8d5f669a",
        city: "1",
        area: "HSR Layout",
        totalRatingsString: "",
        cloudinaryImageId: "exhzkyd9pjoqlobruy4v",
        cuisines: [
          "Biryani",
          "Barbecue",
          "South Indian",
          "Chinese",
          "North Indian",
        ],
        tags: [],
        costForTwo: 65000,
        costForTwoString: "₹650 FOR TWO",
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        slaString: "23 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "dindigul-thalappakatti-hsr",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "HSR Layout",
        parentId: 332,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 6900,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6900,
          message: "",
          title: "Delivery Charge",
          amount: "6900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.1 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=139558&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 23,
          minDeliveryTime: 23,
          maxDeliveryTime: 23,
          lastMileTravel: 0,
          lastMileDistance: 4.1,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "108158",
        name: "Kabab magic",
        uuid: "2fc26cdc-f642-4459-9888-6661c142e8b7",
        city: "1",
        area: "Btm Layout",
        totalRatingsString: "",
        cloudinaryImageId: "aagnmdkdxshwhhtzl7vk",
        cuisines: ["Biryani", "Tandoor", "North Indian", "Mughlai", "Thalis"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 17,
        minDeliveryTime: 17,
        maxDeliveryTime: 17,
        slaString: "17 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "kabab-magic-btm-2",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Maruti Nagar",
        parentId: 527,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 3300,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3300,
          message: "",
          title: "Delivery Charge",
          amount: "3300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.1 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=108158&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 17,
          minDeliveryTime: 17,
          maxDeliveryTime: 17,
          lastMileTravel: 0,
          lastMileDistance: 2.1,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "422917",
        name: "Hyderabad Magic",
        uuid: "f7f997c7-f3bf-4ce6-80a1-08f21da4e439",
        city: "1",
        area: "Bommanahalli",
        totalRatingsString: "",
        cloudinaryImageId: "vm7winbxdem0w9bssxqg",
        cuisines: ["Andhra", "Biryani"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: "26 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "hyderabad-magic-hsr-hsr",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Roopena Agrahara",
        parentId: 21606,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 4100,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4100,
          message: "",
          title: "Delivery Charge",
          amount: "4100",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              description: "",
              shortDescription: "options available",
              fontColor: "#7E808C",
            },
          ],
        },
        lastMileTravelString: "3.8 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=422917&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 0,
          lastMileDistance: 3.8,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "275",
        name: "Mani's Dum Biryani",
        uuid: "6a5627da-e918-431b-ae62-1c2da89324b1",
        city: "1",
        area: "Koramangala",
        totalRatingsString: "",
        cloudinaryImageId: "xlr4ngepa5gxkugrsdbs",
        cuisines: ["Andhra", "Biryani"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 18,
        minDeliveryTime: 18,
        maxDeliveryTime: 18,
        slaString: "18 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "manis-dum-biryani-jyoti-nivas-rd-5th-block-koramangala",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Koramangala",
        parentId: 623,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 3300,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3300,
          message: "",
          title: "Delivery Charge",
          amount: "3300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.6 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=275&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 18,
          minDeliveryTime: 18,
          maxDeliveryTime: 18,
          lastMileTravel: 0,
          lastMileDistance: 1.6,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "523888",
        name: "Biryani Blues",
        uuid: "73eadf01-eba8-4f92-ac81-cc3d662182ab",
        city: "1",
        area: "Koramangala",
        totalRatingsString: "",
        cloudinaryImageId: "xyoqcqwf6bf36jevs1xw",
        cuisines: ["Biryani", "Hyderabadi", "Lucknowi", "Kebabs"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 20,
        minDeliveryTime: 20,
        maxDeliveryTime: 20,
        slaString: "20 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "biryani-blues-koramangala-koramangala",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "7th Block",
        parentId: 13813,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 3300,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3300,
          message: "",
          title: "Delivery Charge",
          amount: "3300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.5 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=523888&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 20,
          minDeliveryTime: 20,
          maxDeliveryTime: 20,
          lastMileTravel: 0,
          lastMileDistance: 2.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "285175",
        name: "Thalairaj Biryani",
        uuid: "d1eef8f7-4254-4491-8c68-2942ca49b9ff",
        city: "1",
        area: "Indiranagar",
        totalRatingsString: "",
        cloudinaryImageId: "g5sfrpdo2x8pjhpk36xm",
        cuisines: [
          "Andhra",
          "Biryani",
          "Hyderabadi",
          "South Indian",
          "Indian",
          "Combo",
          "Beverages",
        ],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: "24 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "thalaivars-biryani-indiranagar-indiranagar",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "2nd stage",
        parentId: 433875,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 6600,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6600,
          message: "",
          title: "Delivery Charge",
          amount: "6600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "5.7 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=285175&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 0,
          lastMileDistance: 5.7,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
];

const ResturantCard = (props) => {
  const { resData } = props;

  const {
    cloudinaryImageId,
    name,
    cuisines,
    avgRating,
    deliveryTime,
    costForTwo,
  } = resData.data.data;

  return (
    <div className="res-card" style={{ backgroundColor: "#f0f0f0" }}>
      <img
        className="res-logo"
        alt="res-img"
        src={
          "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/" +
          cloudinaryImageId
        }
      />
      <h3>{name}</h3>
      <p className="res-desc">
        <span>Cusine : </span>
        {cuisines.join(", ")}
      </p>
      <p className="res-desc">
        <span>Ratings : {avgRating} </span>
        <img
          className="img-star"
          src="https://cdn-icons-png.flaticon.com/128/1828/1828884.png"
        />
      </p>
      <p className="res-desc">
        <span>ETA : </span>
        {deliveryTime} minutes
      </p>
      <p className="res-desc">
        <span>Price : </span>
        {costForTwo / 100} For Two
      </p>
    </div>
  );
};

//key should always be unique and if we are writing a loop we must use a key

const Body = () => {
  return (
    <div className="body">
      <div className="search">Search</div>
      <div className="res-container">
        {resList.map((resturant) => (
          <ResturantCard key={resturant.data.data.id} resData={resturant} />
        ))}
      </div>
    </div>
  );
};

const AppLayout = () => {
  return (
    <div className="app">
      <Header />
      <Body />
      {/* <Footer /> */}
    </div>
  );
};

const root = ReactDOM.createRoot(document.getElementById("root"));

root.render(<AppLayout />); //for calling functional components
//root.render(jsxHeading); //for calling react element
